### ISSUE TITLE
xlrd<2 does not work with python3.9, so pinning it won't help

### ISSUE THREAD

**Issue by berndf** [pyexcel/pyexcel-xls#46]
Hello, referring to #41 and #45 here - xlrd 1.2.0 results in this with python 3.9:

> AttributeError: 'ElementTree' object has no attribute 'getiterator'

Therefore I'd vote to not advertise xlsx support if xlrd>=2 is installed, rather than force an outdated dependency.

**Comment by chfw** [comment]
hmm.. indeed, I can do such a check before the plugin registration.
